# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 智美Love
email: joseph.moghadam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Let the world know: You are the best of the best!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tomomilove.com" # the base hostname & protocol for your site
github_username: jmoghadam

# Build settings
markdown: kramdown

# Tipue search settings
tipue_search:
    include:
        pages: true
