# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Strange World Problem
email: negative.nancy.ng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website for my personal thoughts, trying to make sense of the
  strange world we live in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://strangeproblem.github.io" # the base hostname & protocol for your site
github_username: strangeproblem

# Build settings
markdown: kramdown
